title: My Github Pages
description: I use this site to display my coding projects. This site is new and it will take some time to get the projects over to Github.
github_username: gassims
theme: jekyll-theme-architect
